name: Verify changed pact

on:
  workflow_dispatch:
    inputs:
      pactBrokerURL:
        description: 'Pact broker URL which the verification result will be published'
        required: false
        default: 'http://localhost:9292'
        type: string
      providerVersion:
        description: 'The version of provider on pact record. Suggested value is ${GIT_SHA}'
        required: false
        default: ''
        type: string
      providerVersionBranch:
        description: "The value of provider's branch tag on pact record. Suggested value is ${GIT_BRANCH}"
        required: false
        default: ''
        type: string
      consumerName:
        description: 'The name of consumer on pact record that needs this project to verify. This can be optional'
        required: false
        default: ''
        type: string
      consumerBranch:
        description: "The value of consumer's branch tag on pact record that needs this project to verify. This can be optional"
        required: false
        default: ''
        type: string

env:
  PACT_BROKER_BASE_URL: ${{ github.event.inputs.pactBrokerURL }}
  PACT_BROKER_USERNAME: ${{ secrets.PACT_BROKER_USERNAME }}
  PACT_BROKER_PASSWORD: ${{ secrets.PACT_BROKER_PASSWORD }}
  PROVIDER_VERSION: ${{ github.sha }}
  PROVIDER_VERSION_BRANCH: ${{ github.ref }}
  CONSUMER_NAME: ${{ github.event.inputs.consumerName }}
  CONSUMER_BRANCH: ${{ github.event.inputs.consumerBranch }}

jobs:
  verify-changed-pact:
    runs-on: ubuntu-latest
    steps:
      - name: Update provider version if custom value is provided
        if: ${{ github.event.inputs.providerVersion != '' }}
        run: echo "PROVIDER_VERSION=${{ github.event.inputs.providerVersion }}" >> $GITHUB_ENV
#
      - name: Update provider branch version if custom value is provided
        if: ${{ github.event.inputs.providerVersionBranch != '' }}
        run: echo "PROVIDER_VERSION_BRANCH=${{ github.event.inputs.providerVersionBranch }}" >> $GITHUB_ENV

      - name: Print pactBrokerURL
        run: echo $PACT_BROKER_BASE_URL

      - name: Print providerVersion
        run: echo $PROVIDER_VERSION

      - name: Print providerVersionBranch
        run: echo $PROVIDER_VERSION_BRANCH

      - name: Print Consumer Name
        run: echo $CONSUMER_NAME

      - name: Print Consumer Branch
        run: echo $CONSUMER_BRANCH

      - name: Checkout repository content
        uses: actions/checkout@v3
        with:
          ref: ${{ env.PROVIDER_VERSION_BRANCH }}
          fetch-depth: 0
      - run: git checkout ${{ env.PROVIDER_VERSION }}
