name: Verify changed pact

on:
  workflow_dispatch:
    inputs:
      consumerBranch:
        description: 'Consumer Branch'
        required: true
        default: 'develop'
        type: string
      consumerName:
        description: 'Consumer Name'
        required: true
        default: 'consumer'
        type: string
#  repository_dispatch:
#    types:
#      - pact_changed

env:
  PACT_BROKER_BASE_URL: https://peteac119.pactflow.io
  PACT_BROKER_TOKEN: ${{ secrets.PACTFLOW_TOKEN_FOR_CI_CD_WORKSHOP }}
  PACT_BROKER_PUBLISH_VERIFICATION_RESULTS: true
  GIT_COMMIT: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}
  PACT_URL: ${{ github.event.client_payload.pact_url }}

jobs:
  verify-changed-pact:
    runs-on: ubuntu-latest
    steps:
      - name: Print Consumer Name
        run: echo ${{ github.event.inputs.consumerName }}
      - name: Print Consumer Branch
        run: echo ${{ github.event.inputs.consumerBranch }}
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - run: docker pull pactfoundation/pact-cli:latest
      - name: Install
        run: npm i
      - name: Build
        run: GIT_BRANCH=${GITHUB_REF:11} make ci_webhook
