name: Verify changed pact

on:
  workflow_dispatch:
    inputs:
      pactBrokerURL:
        description: 'Pact broker URL which the verification result will be published'
        required: false
        default: 'http://localhost:9292'
        type: string
      providerVersion:
        description: 'The version of provider on pact record. Suggested value is ${GIT_SHA}'
        required: false
        default: ''
        type: string
      providerVersionBranch:
        description: "The value of provider's branch tag on pact record. Suggested value is ${GIT_BRANCH}"
        required: false
        default: ''
        type: string
      consumerName:
        description: 'The name of consumer on pact record that needs this project to verify. This can be optional'
        required: false
        default: ''
        type: string
      consumerBranch:
        description: "The value of consumer's branch tag on pact record that needs this project to verify. This can be optional"
        required: false
        default: ''
        type: string

#  repository_dispatch:
#    types:
#      - pact_changed

#env:
#  PACT_BROKER_BASE_URL: https://peteac119.pactflow.io
#  PACT_BROKER_TOKEN: ${{ secrets.PACTFLOW_TOKEN_FOR_CI_CD_WORKSHOP }}
#  PACT_BROKER_PUBLISH_VERIFICATION_RESULTS: true
#  GIT_COMMIT: ${{ github.sha }}
#  GITHUB_REF: ${{ github.ref }}
#  PACT_URL: ${{ github.event.client_payload.pact_url }}

jobs:
  verify-changed-pact:
    runs-on: ubuntu-latest
    steps:
      - name: Print pactBrokerURL
        run: echo ${{ github.event.inputs.pactBrokerURL }}

      - name: Print providerVersion
        run: echo ${{ github.event.inputs.providerVersion }}
#        run: echo ${{ github.sha }}

      - name: Print providerVersionBranch
        run: echo ${{ github.event.inputs.providerVersionBranch }}
#        run: echo ${{ github.ref }}

      - name: Print Consumer Name
        run: echo ${{ github.event.inputs.consumerName }}

      - name: Print Consumer Branch
        run: echo ${{ github.event.inputs.consumerBranch }}

      - name: Checkout repository content
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.providerVersion }}

#      - uses: actions/setup-node@v2-beta
#        with:
#          node-version: '12'
#      - run: docker pull pactfoundation/pact-cli:latest
#      - name: Install
#        run: npm i
#      - name: Build
#        run: GIT_BRANCH=${GITHUB_REF:11} make ci_webhook
